"""Initial analytics schema

Revision ID: 0679a039b2e2
Revises: 
Create Date: 2026-07-16 12:16:23.613664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0679a039b2e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('predicted_condition', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('task_duration_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('facility_name', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=255), nullable=True),
    sa.Column('helpful_rating', sa.Integer(), nullable=True),
    sa.Column('clinical_override', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnostic_logs')
    # ### end Alembic commands ###
