"""Add Region and Facility models

Revision ID: 3314527899b9
Revises: 0679a039b2e2
Create Date: 2026-07-16 21:24:13.258171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3314527899b9'
down_revision = '0679a039b2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_diagnostic_logs_facility_id_facilities'), 'facilities', ['facility_id'], ['id'])
        batch_op.drop_column('facility_name')
        batch_op.drop_column('region')

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_regions_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_regions_name'), type_='unique')

    with op.batch_alter_table('diagnostic_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('facility_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_diagnostic_logs_facility_id_facilities'), type_='foreignkey')
        batch_op.drop_column('facility_id')

    # ### end Alembic commands ###
