"""Add Region and Facility models

Revision ID: ef928e95e971
Revises: 0679a039b2e2
Create Date: 2026-07-21 20:55:15.745961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef928e95e971'
down_revision = '0679a039b2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('name', name=op.f('uq_regions_name'))
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_facilities_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    op.drop_table('_alembic_tmp_diagnostic_logs')
    with op.batch_alter_table('diagnostic_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_diagnostic_logs_facility_id_facilities'), 'facilities', ['facility_id'], ['id'])
        batch_op.drop_column('region')
        batch_op.drop_column('facility_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_diagnostic_logs_facility_id_facilities'), type_='foreignkey')
        batch_op.drop_column('facility_id')

    op.create_table('_alembic_tmp_diagnostic_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('predicted_condition', sa.VARCHAR(length=100), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('task_duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=50), nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('helpful_rating', sa.INTEGER(), nullable=True),
    sa.Column('clinical_override', sa.TEXT(), nullable=True),
    sa.Column('facility_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_diagnostic_logs_facility_id_facilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_logs'))
    )
    op.drop_table('facilities')
    op.drop_table('regions')
    # ### end Alembic commands ###
